### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by colorgold** [gabek/node-internet-radio#18]
I get this error whenever I try to get the station information.
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource`
`(Reason: CORS header ‘Access-Control-Allow-Origin’ missing)`

This is the code I am using:
```
var nodeInternetRadio = require("node-internet-radio");
//http://stream.zeno.fm/bmv92smzzbruv
var testStream = "http://stream.zeno.fm/bmv92smzzbruv";
nodeInternetRadio.getStationInfo(testStream, function(error, station) {
  console.log(station);
  //console.log(error);
},nodeInternetRadio.StreamSource.STREAM);
```
I have searched for a solution elsewhere, but I was unable to find any information regarding this problem.

**Comment by gabek** [comment]
Hi there,

I'll look into if there's any way around this.  Does it work if you use the `ICECAST`, `SHOUTCAST_V2`, or `SHOUTCAST_V1` methods?

**Comment by colorgold** [comment]
> SHOUTCAST_V2

I tried with those methods and still did not work.

**Comment by gabek** [comment]
I just put the URL in the `test/integration` test and it seemed to work ok:

```
$ ../../node_modules/.bin/mocha --timeout 10000 test.js

  Try all available methods and return a station object.
{
  title: 'Unknown - Luis Fonsi Ft Ozuna - Imposible.mp3',
  fetchsource: 'STREAM',
  headers: {
    'content-type': 'audio/aac',
    'icy-name': '-',
    'icy-metaint': '16000'
  }
}

```

Are you still seeing errors on the same URL?

**Comment by gabek** [comment]
@colorgold Checking in again.  Are you still seeing this same issue?  I'm still able to get a title back when testing.

```
{
  title: 'Unknown - Baila Asi Pop Charts.mp3',
  fetchsource: 'STREAM',
  headers: {
    'content-type': 'audio/aac',
    'icy-name': '-',
    'icy-metaint': '16000'
  }
}
```

**Comment by gabek** [comment]
Just double checking, you're running this under nodejs, not a browser, correct?

**Comment by gabek** [comment]
No response, can't reproduce.  Closing.  Please re-open if you have more details.

**Comment by colorgold** [comment]
> Just double checking, you're running this under nodejs, not a browser, correct?
Sorry about the delay. I am running this on a browser. How can I do this on my website?

**Comment by gabek** [comment]
This is not compatible with a browser.  It's called `node-internet-radio`, you need to run under Nodejs :)

**Comment by colorgold** [comment]
> This is not compatible with a browser. It's called `node-internet-radio`, you need to run under Nodejs :)

Thank you so much for your reply
