### ISSUE TITLE
Icecast 2.4.2 uses "application/json; charset=UTF-8" as the Content-Type for status-json.xsl

### ISSUE THREAD

**Issue by TheBlackParrot** [gabek/node-internet-radio#3]
Had to change [line 32 of icecast.js](https://github.com/gabek/node-internet-radio/blob/master/lib/icecast.js#L32) from `text/xml` to what's listed for `Content-Type` below:
```
Access-Control-Allow-Origin:*
Cache-Control:no-cache
Content-Length:1285
Content-Type:application/json; charset=UTF-8
Date:Mon, 28 Nov 2016 04:02:01 GMT
Expires:Mon, 26 Jul 1997 05:00:00 GMT
Pragma:no-cache
Server:Icecast 2.4.2
```

**Comment by gabek** [comment]
Interesting, thank you @TheBlackParrot!  Did Icecast change from XML metadata to JSON?

**Comment by TheBlackParrot** [comment]
I think XML is still in Icecast, but you have it hardcoded to fetch and parse only JSON.

**Comment by gabek** [comment]
@TheBlackParrot Sorry I haven't had the time to look into this.  If you already have a fix I'd love a PR!
