### ISSUE TITLE
Feature: .pls format support

### ISSUE THREAD

**Issue by jasonszhao** [gabek/node-internet-radio#5]
node-internet-radio cannot read [PLS files](https://en.wikipedia.org/wiki/PLS_(file_format)). 

PLS files contain simply a list of streaming urls in plaintext **that node-internet-radio can currently read from**. On my macOS, Safari, Firefox, and Chrome all can read PLS files.

**Comment by gabek** [comment]
node-internet-radio takes a stream url and gives back the metadata about it.  Given that a pls (or m3u) file is not a stream I think that's out of scope for what this module is supposed to do.  How you get the stream url to pass to node-internet-radio is up to you.  There are a handful of playlist parsing utilities you can use for that.  Separation of concerns makes me think we should let the parsers do with they're good at and not muddy the waters.
