### ISSUE TITLE
Update lodash due to a security alert

### ISSUE THREAD

**Issue by gabek** [gabek/node-internet-radio#6]
The version of lodash used in this project is being marked as a security alert on Github.  We need to update it and test the library with the new version.

<img width="742" alt="screen shot 2018-10-19 at 5 12 16 pm" src="https://user-images.githubusercontent.com/414923/47248838-2b65ad00-d3c2-11e8-9542-2d06daa9481e.png">

**Comment by parthi82** [comment]
I will take this

**Comment by gabek** [comment]
@parthi82 Awesome, thanks!

**Comment by gabek** [comment]
@parthi82 That's even better!  If you want to pull lodash out and just use `filter` instead then that's a win.

**Comment by parthi82** [comment]
@gabek updated the PR

**Comment by abumalick** [comment]
Can you publish the last version on npm @gabek ?

The security warning is present with 4.2.0

**Comment by gabek** [comment]
Yes!  I'll get that out in the next day or so.

**Comment by gabek** [comment]
Done!

**Comment by abumalick** [comment]
Thank you very much
